import { Inter } from "next/font/google";

import './style/globals.scss'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return children;
}
